sudo: false
language: python
env:
  - RASTERIO_VERSION=0.26.0
addons:
  apt:
    packages:
      - libgdal1h
      - gdal-bin
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/wheelhouse
before_install:
  - "./.travis_riodeps.sh"
install:
  - "pip install -U pip"
  - "pip install --use-wheel --no-index --find-links=$HOME/wheelhouse -e .[test] --cache-dir $HOME/.pip-cache"
  - "pip install --use-wheel -e .[test] --cache-dir $HOME/.pip-cache"
script:
  - py.test --cov mbtiles --cov-report term-missing
after_success:
  - coveralls
